name: "semantic-pull-request"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

permissions:
  pull-requests: read
  statuses: write

jobs:
  main:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
